version: "3.8"

services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      localcert-net:
        ipv4_address: 10.33.44.1
    environment:
      - POSTGRES_DB=unused
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    labels:
      - "traefik.enable=false"

  pdns:
    build: pdns
    restart: unless-stopped
    ports:
      - "8053:53/udp"
    environment:
      - LOCALCERT_PDNS_DB_NAME
      - LOCALCERT_PDNS_DEFAULT_SOA_CONTENT
      - LOCALCERT_PDNS_HOST
      - LOCALCERT_PDNS_WEBSERVER_ALLOW_FROM
      - LOCALCERT_SHARED_PDNS_API_KEY
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      localcert-net:
        ipv4_address: 10.33.44.2
    depends_on:
      - db
    labels:
      - "traefik.enable=false"

  web:
    build: localcert
    restart: unless-stopped
    environment:
      - LOCALCERT_SHARED_PDNS_API_KEY
      - LOCALCERT_WEB_DB_NAME
      - LOCALCERT_WEB_DEBUG
      - LOCALCERT_WEB_DJANGO_SECRET_KEY
      - LOCALCERT_WEB_GITHUB_CLIENT_ID
      - LOCALCERT_WEB_GITHUB_SECRET
      - LOCALCERT_WEB_PDNS_API_PORT
      - LOCALCERT_WEB_PDNS_DNS_PORT
      - LOCALCERT_WEB_PDNS_HOST
      - LOCALCERT_WEB_PGSQL_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      localcert-net:
        ipv4_address: 10.33.44.3
    depends_on:
      - db
      - pdns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.localcert-web.rule=Host(`console.getlocalcert.net`)"
      - "traefik.http.services.localcert-web.loadbalancer.server.port=80"
      - "traefik.docker.network=localcert-net"

  reverse-proxy:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker --api=true --api.dashboard=true --log.level=DEBUG --accesslog=true
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      localcert-net:
        ipv4_address: 10.33.44.4
      default:
    depends_on:
      - web

networks:
  localcert-net:
    name: localcert-net
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.33.44.0/24
          ip_range: 10.33.44.0/26
          gateway: 10.33.44.254
