services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      localcert-net:
        ipv4_address: 192.168.11.1
    environment:
      - POSTGRES_DB=unused
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  pdns:
    build: pdns
    restart: unless-stopped
    ports:
      - "8053:53/udp"
    environment:
      - LOCALCERT_PDNS_DB_NAME
      - LOCALCERT_PDNS_DEFAULT_SOA_CONTENT
      - LOCALCERT_PDNS_HOST
      - LOCALCERT_PDNS_WEBSERVER_ALLOW_FROM
      - LOCALCERT_SHARED_PDNS_API_KEY
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      localcert-net:
        ipv4_address: 192.168.11.2
    depends_on:
      - db

  web:
    build: localcert
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOCALCERT_SHARED_PDNS_API_KEY
      - LOCALCERT_WEB_DB_NAME
      - LOCALCERT_WEB_DEBUG
      - LOCALCERT_WEB_DJANGO_SECRET_KEY
      - LOCALCERT_WEB_GITHUB_CLIENT_ID
      - LOCALCERT_WEB_GITHUB_SECRET
      - LOCALCERT_WEB_PDNS_API_PORT
      - LOCALCERT_WEB_PDNS_DNS_PORT
      - LOCALCERT_WEB_PDNS_HOST
      - LOCALCERT_WEB_PGSQL_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      localcert-net:
        ipv4_address: 192.168.11.3
    depends_on:
      - db
      - pdns

networks:
  localcert-net:
    name: localcert-net
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24
          ip_range: 192.168.11.0/26
          gateway: 192.168.11.254
