services:
  db:
    image: postgres:15.2  # keep in sync with docker-compose-test
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      localcert-net:
        ipv4_address: 10.33.44.1
    environment:
      - POSTGRES_DB=unused
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  web:
    build: localcert
    restart: unless-stopped
    environment:
      - LOCALCERT_PDNS_NS1
      - LOCALCERT_PDNS_NS2
      - LOCALCERT_SHARED_PDNS_API_KEY
      - LOCALCERT_WEB_ACCOUNT_DEFAULT_HTTP_PROTOCOL
      - LOCALCERT_WEB_DB_NAME
      - LOCALCERT_WEB_DEBUG
      - LOCALCERT_WEB_DJANGO_SECRET_KEY
      - LOCALCERT_WEB_GITHUB_CLIENT_ID
      - LOCALCERT_WEB_GITHUB_SECRET
      - LOCALCERT_WEB_PDNS_API_PORT
      - LOCALCERT_WEB_PDNS_DNS_PORT
      - LOCALCERT_WEB_PDNS_HOST
      - LOCALCERT_WEB_PGSQL_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      localcert-net:
        ipv4_address: 10.33.44.3
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.localcert-web.rule=(Host(`console.getlocalcert.net`)) || (Host(`api.getlocalcert.net`) && PathPrefix(`/api/`))"
      - "traefik.http.routers.localcert-web.tls=true"
      - "traefik.http.routers.localcert-web.tls.certresolver=myresolver"
      - "traefik.http.services.localcert-web.loadbalancer.server.port=80"
      - "traefik.docker.network=localcert-net"
      - "traefik.http.routers.localcert-web.entryPoints=websecure"

  reverse-proxy:
    image: traefik:v2.9
    restart: unless-stopped
    ports:
      - "80:80" # KEEP: needed for Let's Encrypt
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    networks:
      localcert-net:
        ipv4_address: 10.33.44.4
      default:
    depends_on:
      - web

networks:
  localcert-net:
    name: localcert-net
    external: false
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 10.33.44.0/24
          ip_range: 10.33.44.0/26
          gateway: 10.33.44.254

