version: "3.8"

services:
  db:
    build: pg-eatmydata
    restart: "no"
    ports:
      - 5432:5432
    environment:
      # TODO: via variable
      - POSTGRES_DB=test_localcert-web
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  pdns:
    build: pdns
    restart: "unless-stopped"
    command: "/app/run.sh"
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      # The Django test DB has a test_ prefix
      - LOCALCERT_WEB_DB_NAME=test_localcert-web
